version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        environment:
            NGINX_ERROR_LOG_LEVEL: 'notice'
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/sites/:/etc/nginx/sites-enabled/:ro
            - ./../Sites/:/var/www/html
            - ./admin:/var/www/html/admin
            - ./logs/nginx/:/var/log/nginx/

    php:
        build: ./php
        container_name: php
        restart: always
        expose:
            - 9000
        external_links:
            - mysql
            - redis
            - rabbitmq
            - postgres
            - memcached
        volumes:
            - ./php/bashrc:/root/.bashrc
            - ./php/php.ini:/etc/php/7.0/fpm/php.ini:ro
            - ./php/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf:ro
            - ./../Sites/:/var/www/html
            - ./admin:/var/www/html/admin
            - ./logs/php:/var/log/

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            - ./logs/mysql:/var/log/
        environment:
            MYSQL_ROOT_PASSWORD: "root"

    memcached:
        image: eeacms/memcached:1.4
        container_name: memcached
        restart: always
        environment:
            MEMCACHED_MEMORY: "256"
        volumes:
            - ./logs/memcached:/var/log/
        ports:
            - "11211:11211"

    redis:
        image: redis:3.2-alpine
        container_name: redis
        restart: always
        volumes:
            - ./redis/data:/data
        ports:
            - "6379:6379"

    rabbitmq:
        image: rabbitmq:3.6-management
        container_name: rabbitmq
        restart: always
        ports:
            - "8080:15672"

    postgres:
        image: postgres:9.6
        container_name: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: 'postgres'
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "9000:9000"

    pgadmin:
        image: foxylion/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            SERVER_MODE: "False"
        external_links:
            - postgres
        volumes:
            - ./postgres/admin:/data
        ports:
            - "5050:80"