version: '2'

services:

    app:
        build: ./build/php
        hostname: app
        container_name: app
        restart: always
        environment:
            NGINX_ERROR_LOG_LEVEL: 'notice'
        ports:
            - "80:80"
            - "443:443"
        external_links:
            - mysql
            - redis
            - rabbitmq
            - postgres
            - memcached
        volumes:
            - ./../Sites:/var/www/html
            - ./admin:/var/www/admin
            - ./config/php/php.ini:/etc/php/7.0/fpm/php.ini:ro
            - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./config/php/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf:ro
            - ./config/php/www.conf:/etc/php/7.0/fpm/pool.d/www.conf:ro
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/nginx/mime.types:/etc/nginx/mime.types:ro
            - ./config/nginx/locations.conf:/etc/nginx/locations.conf:ro
            - ./vhosts/:/etc/nginx/sites-enabled/:ro

    mysql:
        image: mysql:5.7
        hostname: mysql
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        environment:
            MYSQL_ROOT_PASSWORD: "root"

    memcached:
        image: eeacms/memcached:1.4
        hostname: memcached
        container_name: memcached
        restart: always
        environment:
            MEMCACHED_MEMORY: "128"
        ports:
            - "11211:11211"

    portainer:
        image: portainer/portainer
        hostname: portainer
        container_name: portainer
        restart: always
        command: --no-auth --no-analytics
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/portainer:/data
        ports:
            - "9000:9000"