version: '3'

services:

    app:
        build: ./build/php
        hostname: app
        container_name: app
        environment:
            NGINX_ERROR_LOG_LEVEL: 'notice'
        ports:
            - "80:80"
            - "443:443"
        external_links:
            - mysql
            - redis
            - rabbitmq
            - postgres
            - memcached
        volumes:
            - admin:/var/www/admin:nocopy
            - web:/var/www/html:nocopy
            - ./config/php/cli.ini:/etc/php/7.1/cli/conf.d/030-custom.ini:ro
            - ./config/php/fpm.ini:/etc/php/7.1/fpm/conf.d/030-custom.ini:ro
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/nginx/mime.types:/etc/nginx/mime.types:ro
            - ./config/nginx/locations.conf:/etc/nginx/locations.conf:ro
            - ./vhosts/:/etc/nginx/sites-enabled/:ro
        working_dir: "/var/www/html"

    mysql:
        image: mysql
        hostname: mysql
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        environment:
            MYSQL_ROOT_PASSWORD: "root"

    memcached:
        image: memcached
        hostname: memcached
        container_name: memcached
        environment:
            MEMCACHED_MEMORY: "128"
        ports:
            - "11211:11211"

    portainer:
        image: portainer/portainer
        hostname: portainer
        container_name: portainer
        command: --no-auth --no-analytics
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/portainer:/data
        ports:
            - "9000:9000"

volumes:
    web:
        external: true
    admin:
        external: true