version: '2'

services:
    nginx:
        image: nginx:1.11.9
        container_name: nginx
        hostname: nginx
        environment:
            NGINX_ERROR_LOG_LEVEL: 'notice'
        ports:
            - "80:80"
            - "443:443"
        volumes_from:
            - container:web:rw
            - container:admin:rw
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/nginx/mime.types:/etc/nginx/mime.types:ro
            - ./config/nginx/locations.conf:/etc/nginx/locations.conf:ro
            - ./vhosts/:/etc/nginx/sites-enabled/:ro
            - ./logs/nginx/:/var/log/nginx/

    php:
        build: ./build/php
        container_name: php
        hostname: php
        expose:
            - 9000
        external_links:
            - mysql
            - redis
            - rabbitmq
            - postgres
            - memcached
        user:
            root
        volumes_from:
            - container:web:rw
            - container:admin:rw
        volumes:
            - ./build/php/bashrc:/root/.bashrc
            - ./config/php/php.ini:/etc/php/7.0/fpm/php.ini:ro
            - ./config/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./config/php/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf:ro
            - ./config/php/www.conf:/etc/php/7.0/fpm/pool.d/www.conf:ro
            - ./logs/php:/var/log/

    mysql:
        image: mysql:5.7
        container_name: mysql
        hostname: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./config/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            - ./logs/mysql:/var/log/
        environment:
            MYSQL_ROOT_PASSWORD: "root"

    memcached:
        image: eeacms/memcached:1.4
        container_name: memcached
        hostname: memcached
        environment:
            MEMCACHED_MEMORY: "128"
        volumes:
            - ./logs/memcached:/var/log/
        ports:
            - "11211:11211"

    redis:
        image: redis:3.2-alpine
        container_name: redis
        hostname: redis
        volumes:
            - ./data/redis:/data
        ports:
            - "6379:6379"

    rabbitmq:
        image: frodenas/rabbitmq:latest
        container_name: rabbitmq
        hostname: rabbitmq
        environment:
            RABBITMQ_USERNAME: "root"
            RABBITMQ_PASSWORD: "root"
#        volumes:
#            - ./config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
        ports:
            - "15672:15672"
            - "5672:5672"

    postgres:
        image: postgres:9.6
        container_name: postgres
        hostname: postgres
        environment:
            POSTGRES_PASSWORD: 'postgres'
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    portainer:
        image: portainer/portainer
        container_name: portainer
        hostname: portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "9000:9000"

    pgadmin:
        image: foxylion/pgadmin4
        container_name: pgadmin
        hostname: pgadmin
        environment:
            SERVER_MODE: "False"
        external_links:
            - postgres
        volumes:
            - ./data/pgadmin/:/data
        ports:
            - "5050:80"

volumes:
    web:
        external: true